#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Daftar Auto Loader.
|--------------------------------------------------------------------------
|
| Komposer menyediakan loader Class yang mudah dibuat secara otomatis
| untuk aplikasi kita. Kita hanya perlu memanfaatkannya! & Kita akan membutuhkannya
| ke script ini agar kita tidak perlu khawatir dengan
| pemuatan Class kita "secara manual". Merasa senang bisa bersantai.
|
*/

require __DIR__.'/bootstrap/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Running Aplikasi Artisan.
|--------------------------------------------------------------------------
|
| Saat kita menjalankan aplikasi Console, perintah CLI saat ini
| dieksekusi di Console ini dan respon dikirim kembali ke terminal
| atau perangkat output lain untuk pengembang. Tidak ada gunanya!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Shutdown Aplikasi.
|--------------------------------------------------------------------------
|
| Setelah Artisan selesai jalan. Kami akan mematikan secara shutdown
| sehingga setiap pekerjaan akhir bisa dilakukan dengan aplikasi sebelum kita tutup.
| Turunnya proses Ini adalah hal terakhir yang terjadi atas permintaan tersebut.
|
*/

$kernel->terminate($input, $status);

exit($status);
